/**
 * Authoritative Double-Entry Accounting Service for DeskcommCRM.
 *
 * All financial postings generated by microfinance activities (disbursements,
 * repayments, savings deposits, fee collections) must pass through this service,
 * which enforces strict double-entry balance: sum(debit_cents) === sum(credit_cents).
 */

import type {
  JournalEntry,
  JournalEntryRequest,
  JournalLine,
  TrialBalanceAccountSummary,
  TrialBalanceReport,
} from "./types";

export class UnbalancedJournalEntryError extends Error {
  totalDebitCents: number;
  totalCreditCents: number;

  constructor(totalDebitCents: number, totalCreditCents: number) {
    super(
      `Journal entry is unbalanced: Debits (${totalDebitCents}) do not equal Credits (${totalCreditCents}).`,
    );
    this.name = "UnbalancedJournalEntryError";
    this.totalDebitCents = totalDebitCents;
    this.totalCreditCents = totalCreditCents;
  }
}

export class JournalService {
  /**
   * Validates and constructs an authoritative double-entry journal posting.
   * Throws UnbalancedJournalEntryError if Debits != Credits.
   */
  static createJournalEntry(request: JournalEntryRequest): JournalEntry {
    if (!request.lines || request.lines.length < 2) {
      throw new Error("A double-entry journal posting requires at least 2 lines (debit and credit).");
    }

    let totalDebit = 0;
    let totalCredit = 0;

    for (const line of request.lines) {
      if (line.debit_cents < 0 || line.credit_cents < 0) {
        throw new Error("Debit and credit amounts cannot be negative.");
      }
      totalDebit += line.debit_cents;
      totalCredit += line.credit_cents;
    }

    if (totalDebit !== totalCredit) {
      throw new UnbalancedJournalEntryError(totalDebit, totalCredit);
    }

    const entryId = `je-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
    const nowIso = new Date().toISOString();

    const lines: JournalLine[] = request.lines.map((line, idx) => ({
      ...line,
      id: `${entryId}-line-${idx + 1}`,
      organization_id: request.organization_id,
      journal_entry_id: entryId,
      created_at: nowIso,
    }));

    return {
      id: entryId,
      organization_id: request.organization_id,
      entry_date: request.entry_date,
      description: request.description,
      reference_id: request.reference_id,
      reference_type: request.reference_type,
      status: "posted",
      lines,
      created_at: nowIso,
    };
  }

  /**
   * Posts a Loan Disbursement entry:
   *   Debit: 1200 - Loan Receivables (Principal)
   *   Credit: 1000 - Cash & Bank Checking
   */
  static postLoanDisbursement(params: {
    organizationId: string;
    loanId: string;
    principalCents: number;
    description?: string;
  }): JournalEntry {
    const today = new Date().toISOString().split("T")[0] ?? "2026-08-08";
    return this.createJournalEntry({
      organization_id: params.organizationId,
      entry_date: today,
      description: params.description ?? `Loan disbursement for loan #${params.loanId}`,
      reference_id: params.loanId,
      reference_type: "loan_disbursement",
      lines: [
        {
          account_code: "1200",
          account_name: "Microfinance Loan Receivables (Principal)",
          debit_cents: params.principalCents,
          credit_cents: 0,
          memo: `Principal disbursed for loan #${params.loanId}`,
        },
        {
          account_code: "1000",
          account_name: "Cash & Bank Checking",
          debit_cents: 0,
          credit_cents: params.principalCents,
          memo: `Cash outflow for loan #${params.loanId}`,
        },
      ],
    });
  }

  /**
   * Posts a Loan Repayment entry:
   *   Debit: 1000 - Cash & Bank Checking (total payment)
   *   Credit: 1200 - Loan Receivables (principal portion)
   *   Credit: 4200 - Loan Interest Income (interest portion)
   *   Credit: 4300 - Late Payment Penalties (penalty portion, optional)
   */
  static postLoanRepayment(params: {
    organizationId: string;
    loanId: string;
    principalCents: number;
    interestCents: number;
    penaltyCents?: number;
    description?: string;
  }): JournalEntry {
    const today = new Date().toISOString().split("T")[0] ?? "2026-08-08";
    const penalty = params.penaltyCents ?? 0;
    const totalCashCents = params.principalCents + params.interestCents + penalty;

    const lines = [
      {
        account_code: "1000",
        account_name: "Cash & Bank Checking",
        debit_cents: totalCashCents,
        credit_cents: 0,
        memo: `Repayment received for loan #${params.loanId}`,
      },
      {
        account_code: "1200",
        account_name: "Microfinance Loan Receivables (Principal)",
        debit_cents: 0,
        credit_cents: params.principalCents,
        memo: `Principal recovery for loan #${params.loanId}`,
      },
    ];

    if (params.interestCents > 0) {
      lines.push({
        account_code: "4200",
        account_name: "Loan Interest Income",
        debit_cents: 0,
        credit_cents: params.interestCents,
        memo: `Interest earned for loan #${params.loanId}`,
      });
    }

    if (penalty > 0) {
      lines.push({
        account_code: "4300",
        account_name: "Late Payment Penalties & Arrears Fee Income",
        debit_cents: 0,
        credit_cents: penalty,
        memo: `Arrears penalty for loan #${params.loanId}`,
      });
    }

    return this.createJournalEntry({
      organization_id: params.organizationId,
      entry_date: today,
      description: params.description ?? `Loan repayment for loan #${params.loanId}`,
      reference_id: params.loanId,
      reference_type: "loan_repayment",
      lines,
    });
  }

  /**
   * Posts a Savings Deposit entry:
   *   Debit: 1000 - Cash & Bank Checking
   *   Credit: 2100 - Customer Savings & Deposit Accounts
   */
  static postSavingsDeposit(params: {
    organizationId: string;
    clientId: string;
    amountCents: number;
    description?: string;
  }): JournalEntry {
    const today = new Date().toISOString().split("T")[0] ?? "2026-08-08";
    return this.createJournalEntry({
      organization_id: params.organizationId,
      entry_date: today,
      description: params.description ?? `Savings deposit for client #${params.clientId}`,
      reference_id: params.clientId,
      reference_type: "savings_deposit",
      lines: [
        {
          account_code: "1000",
          account_name: "Cash & Bank Checking",
          debit_cents: params.amountCents,
          credit_cents: 0,
          memo: `Cash inflow from savings deposit #${params.clientId}`,
        },
        {
          account_code: "2100",
          account_name: "Customer Savings & Deposit Accounts",
          debit_cents: 0,
          credit_cents: params.amountCents,
          memo: `Deposit liability for client #${params.clientId}`,
        },
      ],
    });
  }

  /**
   * Posts a Savings Withdrawal entry:
   *   Debit: 2100 - Customer Savings & Deposit Accounts
   *   Credit: 1000 - Cash & Bank Checking
   */
  static postSavingsWithdrawal(params: {
    organizationId: string;
    clientId: string;
    amountCents: number;
    description?: string;
  }): JournalEntry {
    const today = new Date().toISOString().split("T")[0] ?? "2026-08-08";
    return this.createJournalEntry({
      organization_id: params.organizationId,
      entry_date: today,
      description: params.description ?? `Savings withdrawal for client #${params.clientId}`,
      reference_id: params.clientId,
      reference_type: "savings_withdrawal",
      lines: [
        {
          account_code: "2100",
          account_name: "Customer Savings & Deposit Accounts",
          debit_cents: params.amountCents,
          credit_cents: 0,
          memo: `Deposit withdrawal for client #${params.clientId}`,
        },
        {
          account_code: "1000",
          account_name: "Cash & Bank Checking",
          debit_cents: 0,
          credit_cents: params.amountCents,
          memo: `Cash outflow from savings withdrawal #${params.clientId}`,
        },
      ],
    });
  }

  /**
   * Posts a Member Share Purchase entry:
   *   Debit: 1000 - Cash & Bank Checking
   *   Credit: 3100 - Member Share Capital
   */
  static postSharePurchase(params: {
    organizationId: string;
    clientId: string;
    amountCents: number;
    description?: string;
  }): JournalEntry {
    const today = new Date().toISOString().split("T")[0] ?? "2026-08-08";
    return this.createJournalEntry({
      organization_id: params.organizationId,
      entry_date: today,
      description: params.description ?? `Member share purchase for client #${params.clientId}`,
      reference_id: params.clientId,
      reference_type: "share_purchase",
      lines: [
        {
          account_code: "1000",
          account_name: "Cash & Bank Checking",
          debit_cents: params.amountCents,
          credit_cents: 0,
          memo: `Cash inflow from member share purchase #${params.clientId}`,
        },
        {
          account_code: "3100",
          account_name: "Member Share Capital",
          debit_cents: 0,
          credit_cents: params.amountCents,
          memo: `Share equity for client #${params.clientId}`,
        },
      ],
    });
  }

  /**
   * Generates an authoritative Trial Balance Report across all journal lines,
   * verifying that total debit balances equal total credit balances.
   */
  static getTrialBalanceReport(
    organizationId: string,
    lines: JournalLine[],
  ): TrialBalanceReport {
    const summaryMap = new Map<string, TrialBalanceAccountSummary>();

    for (const line of lines) {
      const existing = summaryMap.get(line.account_code) ?? {
        account_code: line.account_code,
        account_name: line.account_name,
        total_debit_cents: 0,
        total_credit_cents: 0,
        net_balance_cents: 0,
      };

      existing.total_debit_cents += line.debit_cents;
      existing.total_credit_cents += line.credit_cents;
      existing.net_balance_cents =
        existing.total_debit_cents - existing.total_credit_cents;

      summaryMap.set(line.account_code, existing);
    }

    const accounts = Array.from(summaryMap.values()).sort((a, b) =>
      a.account_code.localeCompare(b.account_code),
    );

    let totalDebits = 0;
    let totalCredits = 0;

    for (const acc of accounts) {
      totalDebits += acc.total_debit_cents;
      totalCredits += acc.total_credit_cents;
    }

    return {
      organization_id: organizationId,
      total_debits_cents: totalDebits,
      total_credits_cents: totalCredits,
      is_balanced: totalDebits === totalCredits,
      accounts,
    };
  }
}
